name: Build and deploy to Azure Container Apps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Вход в Azure
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Получаем учетные данные ACR
      - name: Get ACR credentials
        run: |
          ACR_USERNAME=$(az acr credential show -n ${{ secrets.REGISTRY_NAME }} --query "username" -o tsv)
          ACR_PASSWORD=$(az acr credential show -n ${{ secrets.REGISTRY_NAME }} --query "passwords[0].value" -o tsv)
          echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV

      # Docker login в ACR
      - name: Docker login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_NAME }}.azurecr.io
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      # Сборка и отправка образа используя Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          file: ./Dockerfile
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Создаем или обновляем управляемую идентичность
      - name: Create managed identity if not exists
        run: |
          # Проверяем существует ли идентичность
          IDENTITY_EXISTS=$(az identity list --resource-group ${{ secrets.RESOURCE_GROUP }} --query "[?name=='container-app-identity'].name" -o tsv)
          
          if [ -z "$IDENTITY_EXISTS" ]; then
            # Создаем идентичность
            echo "Creating managed identity..."
            az identity create --name container-app-identity --resource-group ${{ secrets.RESOURCE_GROUP }}
          else
            echo "Managed identity already exists"
          fi
          
          # Получаем ID идентичности
          IDENTITY_ID=$(az identity show --name container-app-identity --resource-group ${{ secrets.RESOURCE_GROUP }} --query id -o tsv)
          PRINCIPAL_ID=$(az identity show --name container-app-identity --resource-group ${{ secrets.RESOURCE_GROUP }} --query principalId -o tsv)
          
          # Сохраняем ID для использования в дальнейшем
          echo "IDENTITY_ID=$IDENTITY_ID" >> $GITHUB_ENV
          echo "PRINCIPAL_ID=$PRINCIPAL_ID" >> $GITHUB_ENV
          
          # Даем идентичности доступ к ACR
          ACR_ID=$(az acr show --name ${{ secrets.REGISTRY_NAME }} --query id -o tsv)
          
          # Проверяем, есть ли уже роль
          ROLE_EXISTS=$(az role assignment list --assignee $PRINCIPAL_ID --scope $ACR_ID --query "[?roleDefinitionName=='AcrPull'].roleDefinitionName" -o tsv)
          
          if [ -z "$ROLE_EXISTS" ]; then
            echo "Assigning AcrPull role..."
            az role assignment create --assignee $PRINCIPAL_ID --role AcrPull --scope $ACR_ID
          else
            echo "Role assignment already exists"
          fi

      # Обновляем или создаем Container App с указанной идентичностью
      - name: Deploy to Azure Container Apps
        run: |
          # Проверяем существует ли Container App
          APP_EXISTS=$(az containerapp show --name ${{ secrets.CONTAINER_APP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} 2>/dev/null || echo "false")
          
          if [ "$APP_EXISTS" = "false" ]; then
            # Создаем новый Container App
            echo "Creating new Container App..."
            az containerapp create \
              --name ${{ secrets.CONTAINER_APP_NAME }} \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --environment ${{ secrets.CONTAINER_APP_ENVIRONMENT }} \
              --image ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ github.sha }} \
              --user-assigned ${{ env.IDENTITY_ID }} \
              --target-port 3000 \
              --ingress external \
              --min-replicas 0 \
              --max-replicas 10
          else
            # Обновляем существующий Container App
            echo "Updating existing Container App..."
            az containerapp update \
              --name ${{ secrets.CONTAINER_APP_NAME }} \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --image ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ github.sha }} \
              --user-assigned ${{ env.IDENTITY_ID }}
          fi 